type ColDef = { key: string; label: string; width: number; numeric?: boolean; date?: boolean };

// Width units are points; landscape letter = 756pt usable
const W = {
  xs: 40,
  sm: 60,
  md: 80,
  lg: 110,
  xl: 140,
  xxl: 180,
};

export const PDF_COLUMNS: Record<string, ColDef[]> = {
  "inventory-per-product": [
    { key: "sku",                  label: "SKU",         width: W.sm },
    { key: "name",                 label: "Ingredient",     width: W.xxl },
    { key: "on_hand_display",      label: "On Hand",     width: W.sm, numeric: true },
    { key: "display_unit",         label: "Unit",        width: W.xs },
    { key: "reorder_point_display",label: "Reorder At",  width: W.sm, numeric: true },
    { key: "reorder_qty_display",  label: "Order Qty",   width: W.sm, numeric: true },
    { key: "is_low_stock",         label: "Low Stock",   width: W.sm },
    { key: "lot_count",            label: "Lots",        width: W.xs, numeric: true },
  ],
  "inventory-detailed": [
    { key: "sku",          label: "SKU",      width: W.sm },
    { key: "product_name", label: "Ingredient",  width: W.xl },
    { key: "lot_code",     label: "Lot",      width: W.md },
    { key: "expires_on",   label: "Expires",  width: W.sm, date: true },
    { key: "is_expired",   label: "Expired",  width: W.xs },
    { key: "on_hand_display", label: "On Hand", width: W.sm, numeric: true },
    { key: "display_unit", label: "Unit",     width: W.xs },
  ],
  "physical-count-sheet": [
    { key: "sku",           label: "SKU",          width: W.sm },
    { key: "name",          label: "Ingredient",      width: W.xl },
    { key: "display_unit",  label: "Unit",         width: W.xs },
    { key: "system_on_hand",label: "System Count", width: W.sm, numeric: true },
    { key: "_counted",      label: "Counted",      width: W.md },
    { key: "_variance",     label: "Variance",     width: W.md },
    { key: "_notes",        label: "Notes",        width: W.xxl },
  ],
  "movements-per-product": [
    { key: "occurred_at",     label: "Date",     width: W.md, date: true },
    { key: "movement_type",   label: "Type",     width: W.sm },
    { key: "display_quantity",label: "Qty",      width: W.sm, numeric: true },
    { key: "display_unit",    label: "Unit",     width: W.xs },
    { key: "lot_code",        label: "Lot",      width: W.md },
    { key: "reason",          label: "Reason",   width: W.xl },
    { key: "performed_by",    label: "By",       width: W.lg },
  ],
  "movements-summary": [
    { key: "day",         label: "Day",       width: W.sm, date: true },
    { key: "sku",         label: "SKU",       width: W.sm },
    { key: "product_name",label: "Ingredient",   width: W.xl },
    { key: "n_check_ins", label: "In #",      width: W.xs, numeric: true },
    { key: "n_check_outs",label: "Out #",     width: W.xs, numeric: true },
    { key: "in_display",  label: "In",        width: W.sm, numeric: true },
    { key: "out_display", label: "Out",       width: W.sm, numeric: true },
    { key: "net_display", label: "Net",       width: W.sm, numeric: true },
    { key: "display_unit",label: "Unit",      width: W.xs },
  ],
  "low-stock": [
    { key: "sku",                    label: "SKU",          width: W.sm },
    { key: "name",                   label: "Ingredient",      width: W.xl },
    { key: "on_hand_display",        label: "On Hand",      width: W.sm, numeric: true },
    { key: "reorder_point_display",  label: "Reorder At",   width: W.sm, numeric: true },
    { key: "shortage_display",       label: "Shortage",     width: W.sm, numeric: true },
    { key: "suggested_order_display",label: "Suggest Order",width: W.sm, numeric: true },
    { key: "display_unit",           label: "Unit",         width: W.xs },
  ],
  "expiring-lots": [
    { key: "expires_on",        label: "Expires",   width: W.sm, date: true },
    { key: "days_until_expiry", label: "Days",      width: W.xs, numeric: true },
    { key: "lot_code",          label: "Lot",       width: W.md },
    { key: "sku",               label: "SKU",       width: W.sm },
    { key: "product_name",      label: "Ingredient",   width: W.xl },
    { key: "on_hand_display",   label: "On Hand",   width: W.sm, numeric: true },
    { key: "display_unit",      label: "Unit",      width: W.xs },
    { key: "is_expired",        label: "Expired",   width: W.xs },
  ],
  "dead-stock": [
    { key: "sku",              label: "SKU",          width: W.sm },
    { key: "name",             label: "Ingredient",      width: W.xl },
    { key: "on_hand_display",  label: "On Hand",      width: W.sm, numeric: true },
    { key: "display_unit",     label: "Unit",         width: W.xs },
    { key: "last_movement_at", label: "Last Movement",width: W.md, date: true },
    { key: "days_inactive",    label: "Days Inactive",width: W.sm, numeric: true },
  ],
  "audit-trail": [
    { key: "occurred_at", label: "When",       width: W.md, date: true },
    { key: "actor_email", label: "Actor",      width: W.xl },
    { key: "action",      label: "Action",     width: W.md },
    { key: "entity_type", label: "Entity",     width: W.sm },
    { key: "entity_id",   label: "ID",         width: W.lg },
  ],
};
